baseURL = "edermi.github.io"
languageCode = "en-us"
title = "edermi's Blog"
theme = "beautifulhugo"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true


[Params]
  commit = "https://github.com/edermi/edermi.github.io/tree/"
  mainSections = ["post","posts"]
  dateFormat = "2006-01-02"
  rss = true
  readingTime = true
  wordCount = true
  hideAuthor = true
  selfHosted = true
  copyright = "CC BY-SA 4.0"

[Author]
  name = "Michael Eder"
  email = "spam-blog@michael-eder.net"
  github = "edermi"
  twitter = "michael_eder_"
  linkedin = "michael-eder-34b923120"
  xing = "Michael_Eder65"


[[menu.main]]
    name = "About"
    url = "about/"
    weight = 1

[[menu.main]]
    name = "Turingcomplete"
    url = "turingcomplete/"
    weight = 3

